on: [push]
env:
  AWS_REGION : "<example-aws-region>" #region here? Something else needed?
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    # These permissions are needed to interact with GitHub's OIDC Token endpoint.
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: zip Lambda function
      -uses: thedoctor0/zip-release@main
       with:
        type: 'zip'
        directory: dynamo_increment.js
        path: /lambda
      - name: Use Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '16.x'
      - name: Install dependencies
      - run: npm install
      - name: configure aws credentials
      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          # where to add permissions if needed on workflow level????
          role-to-assume: arn:aws:iam::696551956218:role/Portfolio_backend_github_role
          aws-region: eu-west-2
      - name: Deploy with CDK
        - name: synth stack
        - run: cdk synth
        - name: deploy stack
        - run: cdk deploy
      - name: Run Cypress test
   